# Generated by Django 3.2.6 on 2021-08-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attach',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
