# Generated by Django 3.2.6 on 2021-08-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='media_root/'),
        ),
    ]
