# Generated by Django 3.2.6 on 2021-08-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attach',
        ),
    ]
